---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/hacbs-integration-tests/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-main-evja
